/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */


// See: https://docs.gradle.org/current/userguide/settings_file_basics.html
// 设置脚本会在任何构建脚本之前求值，这使得它成为启用或配置 全局构建功能 的合适位置，例如插件管理、包含的构建、版本目录等

// SELF NOTE: (might be wrong) but it don't like top-level build.gradle.kts,
// it using different recvier(Settings) and dont affect subproject build.gradle.kts

// See: https://docs.gradle.org/current/userguide/writing_settings_files.html#settings_script_structure
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
    }
}

rootProject.name = "demo"
include("app", "lib")
