/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.android.application)
}

android {
    compileSdk = 33
    namespace = "org.example.application"
    buildFeatures {
        // viewBinding = true
    }
    defaultConfig {
        applicationId = "org.example.application"
        minSdk = 24
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    implementation(project(":lib"))
    // implementation("androidx.fragment:fragment:1.5.1") // 1.7.1 need API34, 1.6.2 will have conflict kotlin stdlib by it's own???
    // implementation("androidx.appcompat:appcompat:1.6.1")
}
